_target_: core.datasets.ZJUH36MDataset
h5_path: data/h36m_zju/${.subject}_train.h5


split: train
patch_size: 1
subject: S5
mask_img: True
perturb_bg: True
bkgd_mul: 1.0
num_train_cams: 3
bkgd_to_use: black