render_dataset:
  _target_: run_render.BaseRenderDataset
  subject: S5
  h5_path: data/h36m_zju/${.subject}_anim.h5
  idxs: np.arange(0,100,5)
  resolution: [1000, 1000]
  cam_overwrite: -1


model_config: logs/danbo_S5_vanilla/config.yaml
output_path: outputs/danbo_S5_vanilla/frames