forward_type: geometry

render_dataset:
  _target_: run_render.MeshRenderDataset
  subject: S5
  h5_path: data/h36m_zju/${.subject}_test.h5
  idxs: np.arange(1)
  mcube_resolution: 384


model_config: logs/danbo_S5_noidentity/config.yaml
output_path: outputs/S5/geometry